namespace SMRSvr.Domain.Enums;

public enum EN_AXIS
{
    AXIS_X = 0,
    AXIS_Y,
    AXIS_Z,
    AXIS_A,
    AXIS_B,
    AXIS_NUM
}

public enum EN_COORDINATE
{
    COORD_G53 = 0,
    COORD_G54,
    COORD_G55,
    COORD_G56,
    COORD_G57,
    COORD_G58,
    COORD_G59,
    COORD_NUM
}

public enum EN_PA_RUN_STATUS
{
    PA_RUN_STATUS_IDLE = 0,
    PA_RUN_STATUS_RUN,
    PA_RUN_STATUS_UNKNOWN,
    PA_RUN_STATUS_ERROR,
    PA_RUN_STATUS_PAUSE,
    PA_RUN_STATUS_NUM
}

public enum EN_RUNMODE
{
    RUNMODE_STOP = 0,
    RUNMODE_TOSTOP,
    RUNMODE_TORUN,
    RUNMODE_RUN,
    RUNMODE_INIT,
    RUNMODE_ERROR,
    RUNMODE_PAUSE,
    RUNMODE_NUM
}

public enum EN_CONNECT_STATUS
{
    CONNECT_STATUS_NOT = 0,
    CONNECT_STATUS_PANDING,
    CONNECT_STATUS_CONNECTED,
    CONNECT_STATUS_NUM
}

public enum EN_NC_FILESTATE
{
    NCFILE_STATE_BEFORE = 0,
    NCFILE_STATE_RUNNING,
    NCFILE_STATE_COMPLETE,
    NCFILE_STATE_STOP,
    NCFILE_STATE_ERROR,
    NCFILE_STATE_NUM
}

public enum EN_IPC_COMMAND
{
    IPC_COMMAND_EMG = 1,
    IPC_COMMAND_RESET = 2,
    IPC_COMMAND_HOME = 3,
    IPC_COMMAND_MODE_SELECT = 4,
    IPC_COMMAND_OPEN = 5,
    IPC_COMMAND_CLOSE = 6,
    IPC_COMMAND_RUN = 7,
    IPC_COMMAND_PAUSE = 8,
    IPC_COMMAND_STOP = 9,
    IPC_COMMAND_OPERMODE = 10,
    IPC_COMMAND_MANUAL = 99
}

public enum EN_AUTOLOADER_BLOCK_STATE
{
    BLOCK_STATE_EMPTY = 0,
    BLOCK_STATE_BEFORE,
    BLOCK_STATE_RUNNING,
    BLOCK_STATE_COMPLETE,
    BLOCK_STATE_ERROR,
    BLOCK_STATE_LOST,
    BLOCK_STATE_NUM
}
